const $=id=>document.getElementById(id),DAY=86400000,WEEK=7*DAY,LS='saferFontanPlanner_v5',OLDLS='saferFontanPlanner_v4';
let state={abs:[],plan:[],reserve:[],replaceId:null,bestFallback:null};
const RES=['Jef','AVDB','PDM','MRI','Hospital'];
function D(s){if(!s)return null;let d=new Date(s+'T12:00:00');return isNaN(d)?null:d}
function iso(d){return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`:''}
function fmt(d){return d?`${String(d.getDate()).padStart(2,'0')}-${String(d.getMonth()+1).padStart(2,'0')}-${d.getFullYear()}`:'—'}
function wd(d){return d?d.toLocaleDateString('nl-BE',{weekday:'short'}):''}
function add(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}
function days(a,b){return Math.round((b-a)/DAY)}function same(a,b){return iso(a)===iso(b)}function uid(){return Math.random().toString(36).slice(2,9)}
function dl(name,text,type='application/json'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),700)}
function easter(y){let f=Math.floor,a=y%19,b=f(y/100),c=y%100,d=f(b/4),e=b%4,g=f((8*b+13)/25),h=(19*a+b-d-g+15)%30,i=f(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=f((a+11*h+19*l)/433),mo=f((h+l-7*m+90)/25),da=(h+l-7*m+33*mo+19)%32;return new Date(y,mo-1,da,12)}
function holidays(y){let e=easter(y);return [new Date(y,0,1,12),add(e,1),new Date(y,4,1,12),add(e,39),add(e,50),new Date(y,6,21,12),new Date(y,7,15,12),new Date(y,10,1,12),new Date(y,10,11,12),new Date(y,11,25,12)]}
function defaultAbs(){return [
{id:uid(),resource:'AVDB',start:'2026-10-06',end:'2026-10-10',reason:'Dender',status:'Hard'},
{id:uid(),resource:'AVDB',start:'2026-11-02',end:'2026-11-08',reason:'Herfstvakantie',status:'Hard'},
{id:uid(),resource:'AVDB',start:'2026-12-21',end:'2027-01-03',reason:'Kerstverlof',status:'Hard'},
{id:uid(),resource:'AVDB',start:'2027-03-29',end:'2027-04-11',reason:'Paasvakantie / mogelijk Korea',status:'Voorlopig'},
{id:uid(),resource:'AVDB',start:'2027-04-09',end:'2027-04-10',reason:'EuroACHD',status:'Hard'},
{id:uid(),resource:'AVDB',start:'2027-06-02',end:'2027-06-05',reason:'Skamania ACHD',status:'Hard'},
{id:uid(),resource:'AVDB',start:'2027-07-15',end:'2027-08-08',reason:'Zomerverlof',status:'Hard'},
{id:uid(),resource:'AVDB',start:'2027-11-01',end:'2027-11-07',reason:'Herfstvakantie',status:'Hard'},
{id:uid(),resource:'AVDB',start:'2027-12-27',end:'2028-01-09',reason:'Kerstverlof',status:'Hard'},
{id:uid(),resource:'AVDB',start:'2028-04-03',end:'2028-04-17',reason:'Paasverlof',status:'Hard'},
{id:uid(),resource:'AVDB',start:'2028-07-15',end:'2028-08-06',reason:'Zomerverlof',status:'Hard'},
{id:uid(),resource:'AVDB',start:'2028-10-30',end:'2028-11-05',reason:'Herfstvakantie',status:'Hard'},
{id:uid(),resource:'AVDB',start:'2028-12-25',end:'2029-01-07',reason:'Kerstverlof',status:'Hard'}]}
function inAbs(date,resource,hardOnly=false){let out=[];for(let a of state.abs){if(a.resource!==resource)continue;let s=D(a.start),e=D(a.end||a.start);if(s&&e&&date>=s&&date<=e&&(!hardOnly||a.status==='Hard'))out.push(a)}if(resource==='Hospital'&&$('holidays').checked){for(let h of holidays(date.getFullYear()))if(same(h,date))out.push({reason:'Wettelijke feestdag',status:'Hard'})}return out}
function hospitalOpen(d){return !inAbs(d,'Hospital',true).length}function hardFree(d,r){return !inAbs(d,r,true).length}
function visitFree(d,type){if(!hospitalOpen(d))return false;if(type==='start')return hardFree(d,'Jef');return ['Jef','AVDB','PDM','MRI'].every(r=>hardFree(d,r))}
function softReasons(d,type){let rs=type==='start'?['Jef']:['Jef','AVDB','PDM','MRI'],out=[];for(let r of rs)for(let a of inAbs(d,r,false))if(a.status!=='Hard')out.push(`${r}: ${a.reason} (voorlopig)`);return out}
function bestStartVisit(anchor){let max=+$('leadDays').value||3,c=[anchor];for(let n=1;n<=max;n++){let d=add(anchor,-n);if([1,2,3].includes(d.getDay()))c.push(d)}for(let d of c)if(visitFree(d,'start'))return {date:d,early:days(d,anchor),soft:softReasons(d,'start')};return null}
function stopOptions(protocol){let out=[];if(visitFree(protocol,'stop'))out.push({date:protocol,day:'Thu',delta:0,soft:softReasons(protocol,'stop')});let tue=add(protocol,-2);if(tue.getDay()===2&&visitFree(tue,'stop'))out.push({date:tue,day:'Tue',delta:-2,soft:softReasons(tue,'stop')});return out}
function baseForAnchor(anchor){let s1=bestStartVisit(anchor),a2=add(anchor,168),s2=bestStartVisit(a2);if(!s1||!s2)return null;let p1=add(anchor,112),p2=add(anchor,280),o1=stopOptions(p1),o2=stopOptions(p2);if(!o1.length||!o2.length)return null;return {anchor,start1:s1.date,a2,start2:s2.date,p1,p2,o1,o2,s1,s2}}
function variant(base,x1,x2){let reasons=[],pen=0,tues=0;if(base.s1.early){reasons.push(`Start 1-visite ${base.s1.early} dag(en) vóór protocolanker`);pen+=base.s1.early}if(base.s2.early){reasons.push(`Start 2-visite ${base.s2.early} dag(en) vóór protocolanker`);pen+=base.s2.early}for(let x of [...base.s1.soft,...base.s2.soft,...x1.soft,...x2.soft]){reasons.push(x);pen+=15}if(x1.day==='Tue'){tues++;reasons.push(`Stop 1 op dinsdag ${fmt(x1.date)} i.p.v. donderdagse protocoldatum ${fmt(base.p1)}`);pen+=100}if(x2.day==='Tue'){tues++;reasons.push(`Stop 2 op dinsdag ${fmt(x2.date)} i.p.v. donderdagse protocoldatum ${fmt(base.p2)}`);pen+=100}let quality=(tues||reasons.some(x=>x.includes('voorlopig')))?'Indien nodig':(base.s1.early||base.s2.early)?'Goed':'Ideaal';return {anchor:base.anchor,start1:base.start1,anchor2:base.a2,start2:base.start2,stop1:x1.date,stop1Protocol:base.p1,stop2:x2.date,stop2Protocol:base.p2,stop1Day:x1.day,stop2Day:x2.day,tues,penalty:pen,quality,reasons}}
function allAnchorBases(){let a=D($('rangeStart').value),b=D($('rangeEnd').value),out=[];if(!a||!b)return out;while(a.getDay()!==4)a=add(a,1);for(let d=a;d<=b;d=add(d,7)){let base=baseForAnchor(d);if(base)out.push(base)}return out}
function strictCandidates(){let out=[];for(let b of allAnchorBases()){let x1=b.o1.find(x=>x.day==='Thu'),x2=b.o2.find(x=>x.day==='Thu');if(x1&&x2)out.push(variant(b,x1,x2))}return out}
function allVariants(){let out=[];for(let b of allAnchorBases())for(let x1 of b.o1)for(let x2 of b.o2)out.push(variant(b,x1,x2));return out}
function chainsFromAnchors(items){let idx=new Map(items.map((x,i)=>[iso(x.anchor),i])),pred=items.map(x=>idx.has(iso(add(x.anchor,-168)))?idx.get(iso(add(x.anchor,-168))):-1),succ=new Map();pred.forEach((p,i)=>{if(p>=0)succ.set(p,i)});let chains=[];pred.forEach((p,i)=>{if(p<0){let ch=[],x=i;while(x!==undefined){ch.push(x);x=succ.get(x)}chains.push(ch)}});return chains}
function strictCapacity(items,prefix=items.length-1){let chains=chainsFromAnchors(items),cap=0;for(let ch of chains){let n=ch.filter(i=>i<=prefix).length;cap+=Math.ceil(n/2)}return cap}
function strictSelect(items,n){if(!items.length||n<=0)return[];let cap=strictCapacity(items);n=Math.min(n,cap);let M=items.length-1;for(let m=0;m<items.length;m++)if(strictCapacity(items,m)>=n){M=m;break}let chains=chainsFromAnchors(items).map(ch=>ch.filter(i=>i<=M));function opts(nodes){let memo=new Map();function rec(pos,prev){let key=pos+'|'+prev;if(memo.has(key))return memo.get(key);if(pos===nodes.length)return new Map([[0,{cost:0,list:[]}]]);let out=new Map();for(let [k,v] of rec(pos+1,0))out.set(k,{cost:v.cost,list:v.list.slice()});if(!prev){let node=nodes[pos];for(let [k,v] of rec(pos+1,1)){let nv={cost:v.cost+items[node].penalty+days(D($('rangeStart').value),items[node].anchor)*0.001,list:[node,...v.list]},old=out.get(k+1);if(!old||nv.cost<old.cost)out.set(k+1,nv)}}memo.set(key,out);return out}return rec(0,0)}let dp=new Map([[0,{cost:0,list:[]}]]);for(let ch of chains){let op=opts(ch),nd=new Map();for(let [k1,v1] of dp)for(let [k2,v2] of op){let k=k1+k2;if(k>n)continue;let nv={cost:v1.cost+v2.cost,list:v1.list.concat(v2.list)},old=nd.get(k);if(!old||nv.cost<old.cost)nd.set(k,nv)}dp=nd}let sol=dp.get(n);return sol?sol.list.sort((a,b)=>a-b).map(i=>items[i]):[]}
function groupVariantsByAnchor(vars,maxAnchor=null){let map=new Map();for(let v of vars){if(maxAnchor&&v.anchor>maxAnchor)continue;let k=iso(v.anchor);if(!map.has(k))map.set(k,[]);map.get(k).push(v)}return [...map.values()].sort((a,b)=>a[0].anchor-b[0].anchor)}
function fallbackSelect(vars,target,maxAnchor=null){let groups=groupVariantsByAnchor(vars,maxAnchor);if(groups.length<target)return null;let idx=new Map(groups.map((g,i)=>[iso(g[0].anchor),i])),pred=groups.map(g=>idx.has(iso(add(g[0].anchor,-168)))?idx.get(iso(add(g[0].anchor,-168))):-1),succ=new Map();pred.forEach((p,i)=>{if(p>=0)succ.set(p,i)});let chains=[];pred.forEach((p,i)=>{if(p<0){let ch=[],x=i;while(x!==undefined){ch.push(x);x=succ.get(x)}chains.push(ch)}});
function better(a,b){if(!b)return true;if(a.tues!==b.tues)return a.tues<b.tues;if(a.pen!==b.pen)return a.pen<b.pen;return a.anchorCost<b.anchorCost}
function chainOpts(nodes){let memo=new Map();function rec(pos,prevSelected,prevS2){let key=`${pos}|${prevSelected}|${prevS2}`;if(memo.has(key))return memo.get(key);if(pos===nodes.length)return new Map([[0,{tues:0,pen:0,anchorCost:0,list:[]}]]);let out=new Map();for(let [k,v] of rec(pos+1,0,'-'))out.set(k,{...v,list:v.list.slice()});let gi=nodes[pos];for(let vi=0;vi<groups[gi].length;vi++){let v=groups[gi][vi];if(prevSelected&&prevS2===v.stop1Day)continue;for(let [k,z] of rec(pos+1,1,v.stop2Day)){let nv={tues:z.tues+v.tues,pen:z.pen+v.penalty,anchorCost:z.anchorCost+days(D($('rangeStart').value),v.anchor),list:[{gi,vi},...z.list]},old=out.get(k+1);if(better(nv,old))out.set(k+1,nv)}}memo.set(key,out);return out}return rec(0,0,'-')}
let dp=new Map([[0,{tues:0,pen:0,anchorCost:0,list:[]}]]);for(let ch of chains){let op=chainOpts(ch),nd=new Map();for(let [k1,v1] of dp)for(let [k2,v2] of op){let k=k1+k2;if(k>target)continue;let nv={tues:v1.tues+v2.tues,pen:v1.pen+v2.pen,anchorCost:v1.anchorCost+v2.anchorCost,list:v1.list.concat(v2.list)},old=nd.get(k);if(better(nv,old))nd.set(k,nv)}dp=nd}let sol=dp.get(target);if(!sol)return null;return {plan:sol.list.map(x=>groups[x.gi][x.vi]).sort((a,b)=>a.anchor-b.anchor),tues:sol.tues,pen:sol.pen}}
function bestFallbackPlan(target){let vars=allVariants(),global=fallbackSelect(vars,target);if(!global)return null;let minTue=global.tues,anchors=[...new Set(vars.map(v=>iso(v.anchor)))].map(D).sort((a,b)=>a-b),best=global;for(let a of anchors){let s=fallbackSelect(vars,target,a);if(s&&s.tues===minTue){best=s;break}}return best}
function assignIds(plan){return plan.map((p,i)=>({...p,id:`P${String(i+1).padStart(2,'0')}`}))}
function autoPlan(){let N=+$('targetN').value||30,strict=strictCandidates(),cap=strictCapacity(strict),n=Math.min(N,cap),sel=strictSelect(strict,n);state.plan=assignIds(sel);state.replaceId=null;state.bestFallback=null;let msg='';if(n===N){msg=`${N} volledig donderdagse combinaties gevonden. Laatste Stop 2: ${fmt(new Date(Math.max(...state.plan.map(p=>p.stop2))))}.`;hideFallback()}else{let fb=bestFallbackPlan(N);state.bestFallback=fb;if(fb){let end=new Date(Math.max(...fb.plan.map(p=>p.stop2))),lastA=new Date(Math.max(...fb.plan.map(p=>p.anchor)));msg=`Maximaal ${n} van ${N} combinaties zijn volledig donderdag zonder Stop-overlap binnen de inclusiedeadline. ${N-n} combinatie(s) ontbreken.`;$('fallbackTitle').textContent=`Volledig ${N}-patiëntenscenario mogelijk met minimaal ${fb.tues} dinsdagse Stop-visite${fb.tues===1?'':'s'}`;$('fallbackText').textContent=`Laatste inclusie ${fmt(lastA)} · laatste Stop 2 ${fmt(end)}. Alle dinsdagmomenten worden als “Indien nodig” gelabeld met exacte reden.`;$('fallbackBox').classList.remove('hidden')}else{msg=`Maximaal ${n} van ${N} volledig donderdagse combinaties gevonden. Ook met dinsdagfallback kan ${N} niet worden bereikt binnen de huidige beschikbaarheden.`;hideFallback()}}buildReserve();render();save();$('message').textContent=msg}
function hideFallback(){$('fallbackBox').classList.add('hidden')}
function useFallback(){if(!state.bestFallback)return;state.plan=assignIds(state.bestFallback.plan);state.replaceId=null;buildReserve();render();save();$('message').textContent=`Fallbackscenario geactiveerd: ${state.plan.length} deelnemers, ${state.bestFallback.tues} dinsdagse Stop-visite(s), overige Stops donderdag.`}
function conflicts(c,excludeId=null){let out=[];for(let p of state.plan){if(p.id===excludeId)continue;if(same(c.stop1,p.stop1)||same(c.stop1,p.stop2)||same(c.stop2,p.stop1)||same(c.stop2,p.stop2))out.push(p.id)}return [...new Set(out)]}
function buildReserve(){let used=new Set(state.plan.map(p=>iso(p.anchor))),arr=[];for(let c of allVariants()){if(used.has(iso(c.anchor)))continue;let cf=conflicts(c,state.replaceId);c={...c,conflicts:cf,category:cf.length===0?(c.tues?'Fallback – vrij':'Reserve – vrij'):cf.length===1?'Vervangt '+cf[0]:`${cf.length} Stop-conflicten`};arr.push(c)}arr.sort((a,b)=>a.conflicts.length-b.conflicts.length||a.tues-b.tues||a.penalty-b.penalty||a.anchor-b.anchor);state.reserve=arr.slice(0,160)}
function qbadge(q){return `<span class="badge ${q==='Ideaal'?'ideal':q==='Goed'?'good':'need'}">${q}</span>`}
function dateCell(actual,protocol){let extra=!same(actual,protocol)?`<div class="weekday redtext">${wd(actual)} · protocol ${fmt(protocol)}</div>`:`<div class="weekday">${wd(actual)}</div>`;return `${fmt(actual)}${extra}`}
function renderPlan(){let tb=$('planBody');tb.innerHTML='';state.plan.slice().sort((a,b)=>a.anchor-b.anchor).forEach(p=>{let tr=document.createElement('tr');tr.innerHTML=`<td><b>${p.id}</b></td><td>${fmt(p.start1)}<div class="weekday">${wd(p.start1)}</div></td><td>${fmt(p.anchor)}<div class="weekday">do</div></td><td>${dateCell(p.stop1,p.stop1Protocol)}</td><td>${fmt(p.start2)}<div class="weekday">${wd(p.start2)}</div></td><td>${fmt(p.anchor2)}<div class="weekday">do</div></td><td>${dateCell(p.stop2,p.stop2Protocol)}</td><td>${qbadge(p.quality)}</td><td class="reason">${p.reasons.join('; ')||'—'}</td><td><button class="btn danger" style="padding:4px 6px" data-fail="${p.id}">Slot mislukt</button></td>`;tb.appendChild(tr)});tb.querySelectorAll('[data-fail]').forEach(b=>b.onclick=()=>failSlot(b.dataset.fail))}
function failSlot(id){state.replaceId=id;state.plan=state.plan.filter(p=>p.id!==id);buildReserve();render();save();showTab('reservePane');$('replaceNote').textContent=`Zoekt vervanging voor ${id}; alle andere combinaties blijven vast.`}
function renderReserve(){let box=$('reserveList');box.innerHTML='';let from=D($('searchFrom').value),showTue=$('showTue').value==='1',list=state.reserve.filter(c=>(!from||c.anchor>=from)&&(showTue||!c.tues)).slice(0,45);if(!list.length){box.innerHTML='<div class="small">Geen alternatieven gevonden.</div>';return}for(let c of list){let d=document.createElement('div');d.className='reserve';let can=c.conflicts.length===0;d.innerHTML=`<div class="toolbar"><b>${fmt(c.anchor)}</b>${qbadge(c.quality)}<span class="badge ${can?'ideal':c.conflicts.length===1?'need':'bad'}">${c.category}</span><button class="btn ${can?'success':'secondary'}" style="margin-left:auto;padding:4px 7px" ${can?'':'disabled'}>Gebruik</button></div><div class="small">Start 1 visite ${fmt(c.start1)} · Stop 1 ${fmt(c.stop1)} (${wd(c.stop1)}) · Start 2 visite ${fmt(c.start2)} · Stop 2 ${fmt(c.stop2)} (${wd(c.stop2)})</div><div class="reason">${c.reasons.join('; ')||'Geen bijzonderheden'}</div>`;if(can)d.querySelector('button').onclick=()=>useReserve(c);box.appendChild(d)}}
function useReserve(c){let id=state.replaceId||`P${String(state.plan.length+1).padStart(2,'0')}`;state.plan.push({...c,id});state.replaceId=null;buildReserve();render();save();$('replaceNote').textContent=''}
function renderAbs(){let tb=$('absBody');tb.innerHTML='';for(let a of state.abs){let tr=document.createElement('tr');tr.innerHTML=`<td><select data-k="resource">${RES.map(r=>`<option ${r===a.resource?'selected':''}>${r}</option>`).join('')}</select></td><td><input data-k="start" type="date" value="${a.start}"></td><td><input data-k="end" type="date" value="${a.end}"></td><td><input data-k="reason" value="${String(a.reason).replaceAll('"','&quot;')}"></td><td><select data-k="status"><option ${a.status==='Hard'?'selected':''}>Hard</option><option ${a.status==='Voorlopig'?'selected':''}>Voorlopig</option></select></td><td><button class="btn danger" style="padding:4px 6px">×</button></td>`;tr.querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{a[el.dataset.k]=el.value;changed()});tr.querySelector('button').onclick=()=>{state.abs=state.abs.filter(x=>x.id!==a.id);renderAbs();changed()};tb.appendChild(tr)}}
function addAbs(){state.abs.push({id:uid(),resource:'Jef',start:iso(new Date()),end:iso(new Date()),reason:'',status:'Hard'});renderAbs();changed()}
function renderKPI(){let p=state.plan;if(!p.length){$('kN').textContent='0';['kStart','kLastStart','kEnd','kWeeks'].forEach(x=>$(x).textContent='—');return}let s=new Date(Math.min(...p.map(x=>x.anchor))),ls=new Date(Math.max(...p.map(x=>x.anchor))),e=new Date(Math.max(...p.map(x=>x.stop2)));$('kN').textContent=p.length;$('kStart').textContent=fmt(s);$('kLastStart').textContent=fmt(ls);$('kEnd').textContent=fmt(e);$('kWeeks').textContent=Math.round((e-s)/WEEK)}
function renderTimeline(){let box=$('timeline');if(!state.plan.length){box.innerHTML='<div class="small" style="padding:12px">Genereer eerst een planning.</div>';return}let min=add(new Date(Math.min(...state.plan.map(p=>p.start1))),-14),max=add(new Date(Math.max(...state.plan.map(p=>p.stop2))),14),span=days(min,max),px=Math.max(2200,span*3.2),left=130,pos=d=>left+(days(min,d)/span)*(px-left-20);let html=`<div class="tl-inner" style="width:${px}px"><div class="tl-axis">`,m=new Date(min.getFullYear(),min.getMonth(),1,12);while(m<=max){html+=`<div class="month" style="left:${pos(m)}px">${m.toLocaleDateString('nl-BE',{month:'short',year:'numeric'})}</div>`;m=new Date(m.getFullYear(),m.getMonth()+1,1,12)}html+='</div>';for(let r of RES){html+=`<div class="lane"><span class="lane-label">${r}</span>`;let abs=state.abs.filter(a=>a.resource===r).map(x=>({...x}));if(r==='Hospital'&&$('holidays').checked)for(let y=min.getFullYear();y<=max.getFullYear();y++)for(let h of holidays(y))abs.push({start:iso(h),end:iso(h),reason:'Feestdag',status:'Hard'});for(let a of abs){let s=D(a.start),e=D(a.end||a.start);if(!s||!e||e<min||s>max)continue;let l=pos(s),w=Math.max(8,pos(add(e,1))-l);html+=`<div class="block ${a.status==='Hard'?'':'soft'}" title="${r}: ${a.reason}" style="left:${l}px;width:${w}px">${a.reason}</div>`}html+='</div>'}for(let p of state.plan.slice().sort((a,b)=>a.anchor-b.anchor)){let l=pos(p.start1),rr=pos(p.stop2);html+=`<div class="lane"><span class="lane-label">${p.id}</span><div class="bar" style="left:${l}px;width:${rr-l}px"></div><i class="mark m-s1" title="Start 1 visite ${fmt(p.start1)} / anker ${fmt(p.anchor)}" style="left:${pos(p.start1)}px"></i><i class="mark m-p1" title="Stop 1 ${fmt(p.stop1)} (${wd(p.stop1)})" style="left:${pos(p.stop1)}px"></i><i class="mark m-s2" title="Start 2 visite ${fmt(p.start2)} / anker ${fmt(p.anchor2)}" style="left:${pos(p.start2)}px"></i><i class="mark m-p2" title="Stop 2 ${fmt(p.stop2)} (${wd(p.stop2)})" style="left:${pos(p.stop2)}px"></i></div>`}html+='</div>';box.innerHTML=html}
function render(){renderPlan();renderReserve();renderKPI();renderTimeline()}
function project(){return {version:5,savedAt:new Date().toISOString(),settings:{rangeStart:$('rangeStart').value,rangeEnd:$('rangeEnd').value,targetN:$('targetN').value,leadDays:$('leadDays').value,holidays:$('holidays').checked},abs:state.abs,plan:state.plan.map(serialise)}}
function serialise(p){let q={...p};for(let k of ['anchor','start1','anchor2','start2','stop1','stop1Protocol','stop2','stop2Protocol'])q[k]=iso(p[k]);return q}
function revive(p){let q={...p};for(let k of ['anchor','start1','anchor2','start2','stop1','stop1Protocol','stop2','stop2Protocol'])q[k]=D(p[k]);return q}
function apply(o){if(!o||!o.settings)throw Error('Ongeldig project');for(let [k,v] of Object.entries(o.settings))if($(k)){if($(k).type==='checkbox')$(k).checked=!!v;else $(k).value=v}state.abs=o.abs||[];state.plan=(o.plan||[]).map(revive);state.replaceId=null;state.bestFallback=null;renderAbs();buildReserve();render();save()}
function save(){try{localStorage.setItem(LS,JSON.stringify(project()));$('saveState').textContent='Lokaal opgeslagen '+new Date().toLocaleTimeString('nl-BE')}catch(e){$('saveState').textContent='Lokale opslag niet beschikbaar'}}function changed(){state.bestFallback=null;hideFallback();buildReserve();render();save()}
async function xlsx(){if(window.XLSX)return true;return await new Promise(res=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=()=>res(true);s.onerror=()=>res(false);document.head.appendChild(s)})}
async function exportSimple(){if(!await xlsx()){alert('Excelmodule kon niet laden.');return}let rows=state.plan.slice().sort((a,b)=>a.anchor-b.anchor).map(p=>({'Patiënt / combinatie':p.id,'Start 1 visite':fmt(p.start1),'Start 1 protocolanker':fmt(p.anchor),'Stop 1 (+16 weken)':fmt(p.stop1),'Stop 1 dag':wd(p.stop1),'Start 2 visite':fmt(p.start2),'Start 2 protocolanker (+24 weken)':fmt(p.anchor2),'Stop 2 (+40 weken)':fmt(p.stop2),'Stop 2 dag':wd(p.stop2),'Beoordeling':p.quality,'Reden indien suboptimaal':p.reasons.join('; ')})),wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:18},{wch:17},{wch:23},{wch:20},{wch:12},{wch:17},{wch:27},{wch:20},{wch:12},{wch:16},{wch:60}];XLSX.utils.book_append_sheet(wb,ws,'Patiëntcombinaties');XLSX.writeFile(wb,'SAFER_Fontan_patientcombinaties.xlsx')}
async function exportFull(){if(!await xlsx()){alert('Excelmodule kon niet laden.');return}let wb=XLSX.utils.book_new(),p=state.plan.map(x=>({ID:x.id,Start1_visite:fmt(x.start1),Start1_anker:fmt(x.anchor),Stop1:fmt(x.stop1),Stop1_dag:wd(x.stop1),Start2_visite:fmt(x.start2),Start2_anker:fmt(x.anchor2),Stop2:fmt(x.stop2),Stop2_dag:wd(x.stop2),Kwaliteit:x.quality,Redenen:x.reasons.join('; ')})),a=state.abs.map(x=>({Resource:x.resource,Start:x.start,Einde:x.end,Reden:x.reason,Status:x.status})),r=state.reserve.slice(0,120).map(x=>({Start1_anker:fmt(x.anchor),Stop1:fmt(x.stop1),Stop1_dag:wd(x.stop1),Start2_anker:fmt(x.anchor2),Stop2:fmt(x.stop2),Stop2_dag:wd(x.stop2),Categorie:x.category,Kwaliteit:x.quality,Redenen:x.reasons.join('; ')})),summary=[{Gepland:state.plan.length,Eerste_start:state.plan.length?fmt(new Date(Math.min(...state.plan.map(x=>x.anchor)))):'',Laatste_inclusie:state.plan.length?fmt(new Date(Math.max(...state.plan.map(x=>x.anchor)))):'',Laatste_Stop2:state.plan.length?fmt(new Date(Math.max(...state.plan.map(x=>x.stop2)))):'',Dinsdagse_Stops:state.plan.reduce((s,x)=>s+x.tues,0)}];XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(summary),'Samenvatting');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(p),'Planning');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(a),'Afwezigheden');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r),'Reserve');XLSX.writeFile(wb,'SAFER_Fontan_planning.xlsx')}
async function exportAbs(){if(!await xlsx()){alert('Excelmodule kon niet laden.');return}let wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(state.abs.map(x=>({Resource:x.resource,Start:x.start,Einde:x.end,Reden:x.reason,Status:x.status})));XLSX.utils.book_append_sheet(wb,ws,'Afwezigheden');XLSX.writeFile(wb,'SAFER_Fontan_afwezigheden.xlsx')}
function parseCSV(t){let lines=t.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim()),delim=(lines[0]||'').includes(';')?';':',';let sp=l=>{let a=[],c='',q=false;for(let i=0;i<l.length;i++){let z=l[i];if(z==='"'){if(q&&l[i+1]==='"'){c+='"';i++}else q=!q}else if(z===delim&&!q){a.push(c);c=''}else c+=z}a.push(c);return a},h=sp(lines.shift()).map(x=>x.trim());return lines.map(l=>{let v=sp(l),o={};h.forEach((k,i)=>o[k]=v[i]||'');return o})}
function importRows(rows){let lc=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k.toLowerCase().trim(),v])),n=0;for(let raw of rows){let o=lc(raw),resource=o.resource||o.persoon||o.wie,start=o.start||o.startdatum||o.van,end=o.einde||o.end||o.einddatum||o.tot,reason=o.reden||o.reason||o.omschrijving||'',status=o.status||'Hard';if(!RES.includes(resource)||!start)continue;let sd=start instanceof Date?iso(start):String(start).slice(0,10),ed=end instanceof Date?iso(end):String(end||start).slice(0,10);state.abs.push({id:uid(),resource,start:sd,end:ed,reason:String(reason),status:String(status).toLowerCase().startsWith('voor')?'Voorlopig':'Hard'});n++}renderAbs();changed();alert(`${n} afwezigheden geïmporteerd.`)}
async function importFile(f){let ext=f.name.split('.').pop().toLowerCase();if(ext==='csv'){let r=new FileReader();r.onload=()=>importRows(parseCSV(r.result));r.readAsText(f)}else{if(!await xlsx()){alert('Excelmodule kon niet laden.');return}let r=new FileReader();r.onload=()=>{let wb=XLSX.read(r.result,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]];importRows(XLSX.utils.sheet_to_json(ws,{defval:'',raw:true}))};r.readAsArrayBuffer(f)}}
function showTab(id){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===id));document.querySelectorAll('.pane').forEach(p=>p.classList.toggle('hidden',p.id!==id))}
function init(){state.abs=defaultAbs();let saved=localStorage.getItem(LS)||localStorage.getItem(OLDLS);if(saved){try{apply(JSON.parse(saved))}catch(e){renderAbs();render();save()}}else{renderAbs();render();save()}$('searchFrom').value=$('rangeStart').value;$('addAbs').onclick=addAbs;$('importAbs').onclick=()=>$('absFile').click();$('absFile').onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]);e.target.value=''};$('exportAbs').onclick=exportAbs;$('autoPlan').onclick=autoPlan;$('useFallback').onclick=useFallback;$('refreshReserve').onclick=()=>{buildReserve();renderReserve();save()};$('findBest').onclick=()=>{buildReserve();renderReserve();showTab('reservePane')};$('exportSimple').onclick=exportSimple;$('exportFull').onclick=exportFull;$('saveProject').onclick=()=>dl('SAFER_Fontan_project.json',JSON.stringify(project(),null,2));$('loadProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{apply(JSON.parse(r.result))}catch(x){alert(x.message)}};r.readAsText(f);e.target.value=''};$('reset').onclick=()=>{if(confirm('Alles resetten?')){localStorage.removeItem(LS);localStorage.removeItem(OLDLS);state={abs:defaultAbs(),plan:[],reserve:[],replaceId:null,bestFallback:null};renderAbs();hideFallback();render();save()}};['rangeStart','rangeEnd','targetN','leadDays','holidays'].forEach(id=>$(id).onchange=changed);$('showTue').onchange=renderReserve;$('searchFrom').onchange=renderReserve;document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>showTab(t.dataset.tab));buildReserve();render()}
init();