const $=id=>document.getElementById(id),DAY=86400000,WEEK=7*DAY,LS='saferFontanPlanner_v5',OLDLS='saferFontanPlanner_v4';
const RES=['Jef','AVDB','PDM','MRI','Hospital'];
let state={abs:[],holidays:[],occupied:[],plan:[],reserve:[],replaceId:null,bestFallback:null};

function D(s){if(!s)return null;let d=s instanceof Date?new Date(s):new Date(String(s).slice(0,10)+'T12:00:00');return isNaN(d)?null:d}
function iso(d){d=D(d);return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`:''}
function fmt(d){d=D(d);return d?`${String(d.getDate()).padStart(2,'0')}-${String(d.getMonth()+1).padStart(2,'0')}-${d.getFullYear()}`:'—'}
function wd(d){d=D(d);return d?d.toLocaleDateString('nl-BE',{weekday:'short'}):''}
function add(d,n){let x=D(d);if(!x)return null;x.setDate(x.getDate()+n);return x}
function days(a,b){a=D(a);b=D(b);return a&&b?Math.round((b-a)/DAY):0}
function same(a,b){return !!a&&!!b&&iso(a)===iso(b)}
function uid(){return Math.random().toString(36).slice(2,9)}
function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function dl(name,text,type='application/json'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),700)}
function resourcesOf(a){if(Array.isArray(a?.resources))return [...new Set(a.resources.filter(r=>RES.includes(r)))];if(a?.resource&&RES.includes(a.resource))return[a.resource];return[]}
function truthy(v){if(v===1||v===true)return true;return ['1','true','yes','ja','y','x','✓','checked'].includes(String(v??'').trim().toLowerCase())}

function easter(y){let f=Math.floor,a=y%19,b=f(y/100),c=y%100,d=f(b/4),e=b%4,g=f((8*b+13)/25),h=(19*a+b-d-g+15)%30,i=f(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=f((a+11*h+19*l)/433),mo=f((h+l-7*m+90)/25),da=(h+l-7*m+33*mo+19)%32;return new Date(y,mo-1,da,12)}
function belgianHolidaysForYear(y){let e=easter(y);return [[new Date(y,0,1,12),'Nieuwjaar'],[add(e,1),'Paasmaandag'],[new Date(y,4,1,12),'Dag van de Arbeid'],[add(e,39),'Hemelvaart'],[add(e,50),'Pinkstermaandag'],[new Date(y,6,21,12),'Nationale feestdag'],[new Date(y,7,15,12),'Onze-Lieve-Vrouw-Hemelvaart'],[new Date(y,10,1,12),'Allerheiligen'],[new Date(y,10,11,12),'Wapenstilstand'],[new Date(y,11,25,12),'Kerstmis']]}
function defaultHolidays(){let out=[];for(let y=2026;y<=2030;y++)for(let [d,name] of belgianHolidaysForYear(y))out.push({id:`be_${iso(d)}`,date:iso(d),name,enabled:true,custom:false});return out}
function defaultAbs(){return [
{id:uid(),resources:['AVDB'],start:'2026-10-06',end:'2026-10-10',reason:'Dender',status:'Hard'},
{id:uid(),resources:['AVDB'],start:'2026-11-02',end:'2026-11-08',reason:'Herfstvakantie',status:'Hard'},
{id:uid(),resources:['AVDB'],start:'2026-12-21',end:'2026-12-27',reason:'Kerstverlof',status:'Hard'},
{id:uid(),resources:['AVDB'],start:'2027-03-29',end:'2027-04-11',reason:'Paasvakantie / mogelijk Korea',status:'Voorlopig'},
{id:uid(),resources:['AVDB'],start:'2027-04-09',end:'2027-04-10',reason:'EuroACHD',status:'Hard'},
{id:uid(),resources:['AVDB'],start:'2027-06-02',end:'2027-06-05',reason:'Skamania ACHD',status:'Hard'},
{id:uid(),resources:['AVDB'],start:'2027-07-15',end:'2027-08-08',reason:'Zomerverlof',status:'Hard'},
{id:uid(),resources:['AVDB'],start:'2027-11-01',end:'2027-11-07',reason:'Herfstvakantie',status:'Hard'},
{id:uid(),resources:['AVDB'],start:'2027-12-20',end:'2027-12-26',reason:'Kerstverlof',status:'Hard'},
{id:uid(),resources:['AVDB'],start:'2028-04-03',end:'2028-04-17',reason:'Paasverlof',status:'Hard'},
{id:uid(),resources:['AVDB'],start:'2028-07-15',end:'2028-08-06',reason:'Zomerverlof',status:'Hard'},
{id:uid(),resources:['AVDB'],start:'2028-10-30',end:'2028-11-05',reason:'Herfstvakantie',status:'Hard'},
{id:uid(),resources:['AVDB'],start:'2028-12-25',end:'2029-01-07',reason:'Kerstverlof',status:'Hard'}]}
function normaliseAbs(a){return{id:a.id||uid(),resources:resourcesOf(a),start:iso(a.start),end:iso(a.end||a.start),reason:String(a.reason||''),status:String(a.status||'Hard').toLowerCase().startsWith('voor')?'Voorlopig':'Hard'}}
function normaliseHoliday(h){return{id:h.id||uid(),date:iso(h.date),name:String(h.name||h.reason||'Sluitingsdag'),enabled:h.enabled!==false,custom:!!h.custom}}
function normaliseOccupied(o){let anchor=iso(o.anchor||o.start1Anchor||o.start1_anker||''),a=D(anchor);let anchor2=o.anchor2?iso(o.anchor2):(a?iso(add(a,168)):'');return{id:o.id||o.patient||o.patientId||`Bezet ${uid()}`,anchor,start1:iso(o.start1||o.start1Visit||anchor),stop1:iso(o.stop1||(a?add(a,112):'')),anchor2,start2:iso(o.start2||o.start2Visit||anchor2),stop2:iso(o.stop2||(a?add(a,280):'')),note:String(o.note||o.opmerking||'')}}
function activeHolidayOn(d){let k=iso(d);return state.holidays.find(h=>h.enabled&&h.date===k)}
function inAbs(date,resource,hardOnly=false){let out=[];for(let a of state.abs){if(!resourcesOf(a).includes(resource))continue;let s=D(a.start),e=D(a.end||a.start);if(s&&e&&date>=s&&date<=e&&(!hardOnly||a.status==='Hard'))out.push(a)}if(resource==='Hospital'){let h=activeHolidayOn(date);if(h)out.push({reason:h.name,status:'Hard',holiday:true})}return out}
function hospitalOpen(d){return !inAbs(d,'Hospital',true).length}
function hardFree(d,r){return !inAbs(d,r,true).length}
function visitFree(d,type){if(!hospitalOpen(d))return false;if(type==='start')return hardFree(d,'Jef');return ['Jef','AVDB','PDM','MRI'].every(r=>hardFree(d,r))}
function softReasons(d,type){let rs=type==='start'?['Jef']:['Jef','AVDB','PDM','MRI'],out=[];for(let r of rs)for(let a of inAbs(d,r,false))if(a.status!=='Hard')out.push(`${r}: ${a.reason} (voorlopig)`);return out}
function bestStartVisit(anchor){let max=+$('leadDays').value||3,c=[D(anchor)];for(let n=1;n<=max;n++){let d=add(anchor,-n);if([1,2,3].includes(d.getDay()))c.push(d)}for(let d of c)if(visitFree(d,'start'))return{date:d,early:days(d,anchor),soft:softReasons(d,'start')};return null}
function stopOptions(protocol){let out=[];if(visitFree(protocol,'stop'))out.push({date:D(protocol),day:'Thu',delta:0,soft:softReasons(protocol,'stop')});let tue=add(protocol,-2);if(tue&&tue.getDay()===2&&visitFree(tue,'stop'))out.push({date:tue,day:'Tue',delta:-2,soft:softReasons(tue,'stop')});return out}
function baseForAnchor(anchor){let s1=bestStartVisit(anchor),a2=add(anchor,168),s2=bestStartVisit(a2);if(!s1||!s2)return null;let p1=add(anchor,112),p2=add(anchor,280),o1=stopOptions(p1),o2=stopOptions(p2);if(!o1.length||!o2.length)return null;return{anchor:D(anchor),start1:s1.date,a2,start2:s2.date,p1,p2,o1,o2,s1,s2}}
function variant(base,x1,x2){let reasons=[],pen=0,tues=0;if(base.s1.early){reasons.push(`Start 1-visite ${base.s1.early} dag(en) vóór protocolanker`);pen+=base.s1.early}if(base.s2.early){reasons.push(`Start 2-visite ${base.s2.early} dag(en) vóór protocolanker`);pen+=base.s2.early}for(let x of [...base.s1.soft,...base.s2.soft,...x1.soft,...x2.soft]){reasons.push(x);pen+=15}if(x1.day==='Tue'){tues++;reasons.push(`Stop 1 op dinsdag ${fmt(x1.date)} i.p.v. donderdagse protocoldatum ${fmt(base.p1)}`);pen+=100}if(x2.day==='Tue'){tues++;reasons.push(`Stop 2 op dinsdag ${fmt(x2.date)} i.p.v. donderdagse protocoldatum ${fmt(base.p2)}`);pen+=100}let quality=(tues||reasons.some(x=>x.includes('voorlopig')))?'Indien nodig':(base.s1.early||base.s2.early)?'Goed':'Ideaal';return{anchor:base.anchor,start1:base.start1,anchor2:base.a2,start2:base.start2,stop1:x1.date,stop1Protocol:base.p1,stop2:x2.date,stop2Protocol:base.p2,stop1Day:x1.day,stop2Day:x2.day,tues,penalty:pen,quality,reasons}}
function occupiedStopMap(){let m=new Map();for(let o of state.occupied){for(let k of ['stop1','stop2'])if(o[k]){let d=iso(o[k]);if(d)m.set(d,(m.get(d)||[]).concat(o.id))}}return m}
function occupiedConflict(c){let m=occupiedStopMap(),ids=[];for(let d of [iso(c.stop1),iso(c.stop2)])if(m.has(d))ids.push(...m.get(d));return[...new Set(ids)]}
function allAnchorBases(){let a=D($('rangeStart').value),b=D($('rangeEnd').value),out=[];if(!a||!b)return out;while(a.getDay()!==4)a=add(a,1);for(let d=a;d<=b;d=add(d,7)){let base=baseForAnchor(d);if(base)out.push(base)}return out}
function strictCandidates(){let out=[];for(let b of allAnchorBases()){let x1=b.o1.find(x=>x.day==='Thu'),x2=b.o2.find(x=>x.day==='Thu');if(x1&&x2){let v=variant(b,x1,x2);if(!occupiedConflict(v).length)out.push(v)}}return out}
function allVariants(){let out=[];for(let b of allAnchorBases())for(let x1 of b.o1)for(let x2 of b.o2){let v=variant(b,x1,x2);if(!occupiedConflict(v).length)out.push(v)}return out}
function chainsFromAnchors(items){let idx=new Map(items.map((x,i)=>[iso(x.anchor),i])),pred=items.map(x=>idx.has(iso(add(x.anchor,-168)))?idx.get(iso(add(x.anchor,-168))):-1),succ=new Map();pred.forEach((p,i)=>{if(p>=0)succ.set(p,i)});let chains=[];pred.forEach((p,i)=>{if(p<0){let ch=[],x=i;while(x!==undefined){ch.push(x);x=succ.get(x)}chains.push(ch)}});return chains}
function strictCapacity(items,prefix=items.length-1){if(!items.length)return 0;let chains=chainsFromAnchors(items),cap=0;for(let ch of chains){let n=ch.filter(i=>i<=prefix).length;cap+=Math.ceil(n/2)}return cap}
function strictSelect(items,n){if(!items.length||n<=0)return[];let cap=strictCapacity(items);n=Math.min(n,cap);let M=items.length-1;for(let m=0;m<items.length;m++)if(strictCapacity(items,m)>=n){M=m;break}let chains=chainsFromAnchors(items).map(ch=>ch.filter(i=>i<=M));function opts(nodes){let memo=new Map();function rec(pos,prev){let key=pos+'|'+prev;if(memo.has(key))return memo.get(key);if(pos===nodes.length)return new Map([[0,{cost:0,list:[]}]]);let out=new Map();for(let [k,v] of rec(pos+1,0))out.set(k,{cost:v.cost,list:v.list.slice()});if(!prev){let node=nodes[pos];for(let [k,v] of rec(pos+1,1)){let nv={cost:v.cost+items[node].penalty+days(D($('rangeStart').value),items[node].anchor)*0.001,list:[node,...v.list]},old=out.get(k+1);if(!old||nv.cost<old.cost)out.set(k+1,nv)}}memo.set(key,out);return out}return rec(0,0)}let dp=new Map([[0,{cost:0,list:[]}]]);for(let ch of chains){let op=opts(ch),nd=new Map();for(let [k1,v1] of dp)for(let [k2,v2] of op){let k=k1+k2;if(k>n)continue;let nv={cost:v1.cost+v2.cost,list:v1.list.concat(v2.list)},old=nd.get(k);if(!old||nv.cost<old.cost)nd.set(k,nv)}dp=nd}let sol=dp.get(n);return sol?sol.list.sort((a,b)=>a-b).map(i=>items[i]):[]}
function groupVariantsByAnchor(vars,maxAnchor=null){let map=new Map();for(let v of vars){if(maxAnchor&&v.anchor>maxAnchor)continue;let k=iso(v.anchor);if(!map.has(k))map.set(k,[]);map.get(k).push(v)}return[...map.values()].sort((a,b)=>a[0].anchor-b[0].anchor)}
function fallbackSelect(vars,target,maxAnchor=null){if(target<=0)return{plan:[],tues:0,pen:0};let groups=groupVariantsByAnchor(vars,maxAnchor);if(groups.length<target)return null;let idx=new Map(groups.map((g,i)=>[iso(g[0].anchor),i])),pred=groups.map(g=>idx.has(iso(add(g[0].anchor,-168)))?idx.get(iso(add(g[0].anchor,-168))):-1),succ=new Map();pred.forEach((p,i)=>{if(p>=0)succ.set(p,i)});let chains=[];pred.forEach((p,i)=>{if(p<0){let ch=[],x=i;while(x!==undefined){ch.push(x);x=succ.get(x)}chains.push(ch)}});function better(a,b){if(!b)return true;if(a.tues!==b.tues)return a.tues<b.tues;if(a.pen!==b.pen)return a.pen<b.pen;return a.anchorCost<b.anchorCost}function chainOpts(nodes){let memo=new Map();function rec(pos,prevSelected,prevS2){let key=`${pos}|${prevSelected}|${prevS2}`;if(memo.has(key))return memo.get(key);if(pos===nodes.length)return new Map([[0,{tues:0,pen:0,anchorCost:0,list:[]}]]);let out=new Map();for(let [k,v] of rec(pos+1,0,'-'))out.set(k,{...v,list:v.list.slice()});let gi=nodes[pos];for(let vi=0;vi<groups[gi].length;vi++){let v=groups[gi][vi];if(prevSelected&&prevS2===v.stop1Day)continue;for(let [k,z] of rec(pos+1,1,v.stop2Day)){let nv={tues:z.tues+v.tues,pen:z.pen+v.penalty,anchorCost:z.anchorCost+days(D($('rangeStart').value),v.anchor),list:[{gi,vi},...z.list]},old=out.get(k+1);if(better(nv,old))out.set(k+1,nv)}}memo.set(key,out);return out}return rec(0,0,'-')}let dp=new Map([[0,{tues:0,pen:0,anchorCost:0,list:[]}]]);for(let ch of chains){let op=chainOpts(ch),nd=new Map();for(let [k1,v1] of dp)for(let [k2,v2] of op){let k=k1+k2;if(k>target)continue;let nv={tues:v1.tues+v2.tues,pen:v1.pen+v2.pen,anchorCost:v1.anchorCost+v2.anchorCost,list:v1.list.concat(v2.list)},old=nd.get(k);if(better(nv,old))nd.set(k,nv)}dp=nd}let sol=dp.get(target);if(!sol)return null;return{plan:sol.list.map(x=>groups[x.gi][x.vi]).sort((a,b)=>a.anchor-b.anchor),tues:sol.tues,pen:sol.pen}}
function bestFallbackPlan(target){let vars=allVariants(),global=fallbackSelect(vars,target);if(!global)return null;let minTue=global.tues,anchors=[...new Set(vars.map(v=>iso(v.anchor)))].map(D).sort((a,b)=>a-b),best=global;for(let a of anchors){let s=fallbackSelect(vars,target,a);if(s&&s.tues===minTue){best=s;break}}return best}
function assignIds(plan){return plan.map((p,i)=>({...p,id:`Slot ${String(i+1).padStart(2,'0')}`}))}
function combinedEnd(extraPlan=state.plan){let ds=[...state.occupied.map(o=>D(o.stop2)).filter(Boolean),...extraPlan.map(p=>D(p.stop2)).filter(Boolean)];return ds.length?new Date(Math.max(...ds)):null}
function combinedLastAnchor(extraPlan=state.plan){let ds=[...state.occupied.map(o=>D(o.anchor)).filter(Boolean),...extraPlan.map(p=>D(p.anchor)).filter(Boolean)];return ds.length?new Date(Math.max(...ds)):null}
function combinedFirstAnchor(extraPlan=state.plan){let ds=[...state.occupied.map(o=>D(o.anchor)).filter(Boolean),...extraPlan.map(p=>D(p.anchor)).filter(Boolean)];return ds.length?new Date(Math.min(...ds)):null}
function autoPlan(){let target=+$('targetN').value||30,locked=state.occupied.length,need=Math.max(0,target-locked);state.replaceId=null;state.bestFallback=null;if(need===0){state.plan=[];hideFallback();render();save();$('message').textContent=`Er zijn al ${locked} ingenomen sloten voor een doel van ${target}. Geen extra planning nodig.`;return}let strict=strictCandidates(),cap=strictCapacity(strict),n=Math.min(need,cap),sel=strictSelect(strict,n);state.plan=assignIds(sel);let msg='';if(n===need){hideFallback();msg=`${locked} reeds ingenomen + ${need} nieuwe volledig-donderdagse combinaties. Totale doelbezetting: ${locked+need}/${target}.`}else{let fb=bestFallbackPlan(need);state.bestFallback=fb;if(fb){let end=combinedEnd(fb.plan),lastA=combinedLastAnchor(fb.plan);msg=`Met de huidige vaste sloten zijn ${n} van de ${need} resterende patiënten volledig donderdag haalbaar. ${need-n} ontbreken zonder fallback.`;$('fallbackTitle').textContent=`Volledig doel van ${target} mogelijk met minimaal ${fb.tues} dinsdagse Stop-visite${fb.tues===1?'':'s'} in de nieuwe planning`;$('fallbackText').textContent=`${locked} slot(en) blijven vast · laatste nieuwe inclusie ${fmt(lastA)} · totale laatste Stop 2 ${fmt(end)}. De tool kiest binnen het minimale aantal dinsdagfallbacks de vroegst eindigende planning.`;$('fallbackBox').classList.remove('hidden')}else{hideFallback();msg=`${locked} reeds ingenomen. Maximaal ${n} extra volledig-donderdagse combinaties gevonden; ook met dinsdagfallback kan het totaal van ${target} niet worden bereikt binnen de huidige deadline/beschikbaarheden.`}}buildReserve();render();save();$('message').textContent=msg}
function hideFallback(){if($('fallbackBox'))$('fallbackBox').classList.add('hidden')}
function useFallback(){if(!state.bestFallback)return;state.plan=assignIds(state.bestFallback.plan);state.replaceId=null;buildReserve();render();save();$('message').textContent=`Fallbackscenario geactiveerd: ${state.occupied.length} vast + ${state.plan.length} nieuw; ${state.bestFallback.tues} dinsdagse Stop-visite(s) in de nieuwe planning.`}
function conflicts(c,excludeId=null){let out=[];for(let p of state.plan){if(p.id===excludeId)continue;if(same(c.stop1,p.stop1)||same(c.stop1,p.stop2)||same(c.stop2,p.stop1)||same(c.stop2,p.stop2))out.push(p.id)}for(let id of occupiedConflict(c))out.push(`Vast: ${id}`);return[...new Set(out)]}
function buildReserve(){let used=new Set(state.plan.map(p=>iso(p.anchor))),arr=[];for(let c of allVariants()){if(used.has(iso(c.anchor)))continue;let cf=conflicts(c,state.replaceId);c={...c,conflicts:cf,category:cf.length===0?(c.tues?'Fallback – vrij':'Reserve – vrij'):cf.length===1?'Conflict: '+cf[0]:`${cf.length} Stop-conflicten`};arr.push(c)}arr.sort((a,b)=>a.conflicts.length-b.conflicts.length||a.tues-b.tues||a.penalty-b.penalty||a.anchor-b.anchor);state.reserve=arr.slice(0,180)}
function qbadge(q){return`<span class="badge ${q==='Ideaal'?'ideal':q==='Goed'?'good':'need'}">${q}</span>`}
function dateCell(actual,protocol){let extra=!same(actual,protocol)?`<div class="weekday redtext">${wd(actual)} · protocol ${fmt(protocol)}</div>`:`<div class="weekday">${wd(actual)}</div>`;return`${fmt(actual)}${extra}`}
function renderPlan(){let tb=$('planBody');tb.innerHTML='';state.plan.slice().sort((a,b)=>a.anchor-b.anchor).forEach(p=>{let tr=document.createElement('tr');tr.innerHTML=`<td><b>${esc(p.id)}</b></td><td>${fmt(p.start1)}<div class="weekday">${wd(p.start1)}</div></td><td>${fmt(p.anchor)}<div class="weekday">do</div></td><td>${dateCell(p.stop1,p.stop1Protocol)}</td><td>${fmt(p.start2)}<div class="weekday">${wd(p.start2)}</div></td><td>${fmt(p.anchor2)}<div class="weekday">do</div></td><td>${dateCell(p.stop2,p.stop2Protocol)}</td><td>${qbadge(p.quality)}</td><td class="reason">${esc(p.reasons.join('; ')||'—')}</td><td class="nowrap"><button class="btn success" style="padding:4px 6px" data-lock="${esc(p.id)}">Maak bezet</button> <button class="btn danger" style="padding:4px 6px" data-fail="${esc(p.id)}">Slot mislukt</button></td>`;tb.appendChild(tr)});tb.querySelectorAll('[data-fail]').forEach(b=>b.onclick=()=>failSlot(b.dataset.fail));tb.querySelectorAll('[data-lock]').forEach(b=>b.onclick=()=>markOccupied(b.dataset.lock))}
function failSlot(id){state.replaceId=id;state.plan=state.plan.filter(p=>p.id!==id);buildReserve();render();save();showTab('reservePane');$('replaceNote').textContent=`Zoekt vervanging voor ${id}; alle overige nieuwe én reeds ingenomen sloten blijven vast.`}
function markOccupied(id){let p=state.plan.find(x=>x.id===id);if(!p)return;let label=prompt('Patiënt-ID / label voor dit ingenomen slot:',id);if(label===null)return;state.occupied.push(normaliseOccupied({id:label.trim()||id,anchor:p.anchor,start1:p.start1,stop1:p.stop1,anchor2:p.anchor2,start2:p.start2,stop2:p.stop2,note:p.quality==='Ideaal'?'':p.reasons.join('; ')}));state.plan=state.plan.filter(x=>x.id!==id);renderOccupied();save();autoPlan()}
function renderReserve(){let box=$('reserveList');box.innerHTML='';let from=D($('searchFrom').value),showTue=$('showTue').value==='1',list=state.reserve.filter(c=>(!from||c.anchor>=from)&&(showTue||!c.tues)).slice(0,50);if(!list.length){box.innerHTML='<div class="small">Geen alternatieven gevonden.</div>';return}for(let c of list){let d=document.createElement('div');d.className='reserve';let can=c.conflicts.length===0;d.innerHTML=`<div class="toolbar"><b>${fmt(c.anchor)}</b>${qbadge(c.quality)}<span class="badge ${can?'ideal':c.conflicts.length===1?'need':'bad'}">${esc(c.category)}</span><button class="btn ${can?'success':'secondary'}" style="margin-left:auto;padding:4px 7px" ${can?'':'disabled'}>Gebruik</button></div><div class="small">Start 1 visite ${fmt(c.start1)} · Stop 1 ${fmt(c.stop1)} (${wd(c.stop1)}) · Start 2 visite ${fmt(c.start2)} · Stop 2 ${fmt(c.stop2)} (${wd(c.stop2)})</div><div class="reason">${esc(c.reasons.join('; ')||'Geen bijzonderheden')}</div>`;if(can)d.querySelector('button').onclick=()=>useReserve(c);box.appendChild(d)}}
function useReserve(c){let id=state.replaceId||`Slot ${String(state.plan.length+1).padStart(2,'0')}`;state.plan.push({...c,id});state.replaceId=null;buildReserve();render();save();$('replaceNote').textContent=''}
function renderAbs(){let tb=$('absBody');tb.innerHTML='';for(let a of state.abs){a.resources=resourcesOf(a);let tr=document.createElement('tr');tr.innerHTML=`<td><input data-k="start" type="date" value="${esc(a.start)}"></td><td><input data-k="end" type="date" value="${esc(a.end)}"></td><td><input data-k="reason" type="text" value="${esc(a.reason)}"></td><td><select data-k="status"><option ${a.status==='Hard'?'selected':''}>Hard</option><option ${a.status==='Voorlopig'?'selected':''}>Voorlopig</option></select></td>${RES.map(r=>`<td class="resource-check"><input type="checkbox" data-r="${r}" ${a.resources.includes(r)?'checked':''}></td>`).join('')}<td><button class="btn danger" style="padding:4px 6px">×</button></td>`;tr.querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{a[el.dataset.k]=el.value;changed()});tr.querySelectorAll('[data-r]').forEach(el=>el.onchange=()=>{a.resources=RES.filter(r=>tr.querySelector(`[data-r="${r}"]`)?.checked);changed()});tr.querySelector('button').onclick=()=>{state.abs=state.abs.filter(x=>x.id!==a.id);renderAbs();changed()};tb.appendChild(tr)}}
function addAbs(){state.abs.push({id:uid(),resources:['Jef'],start:iso(new Date()),end:iso(new Date()),reason:'',status:'Hard'});renderAbs();changed()}
function renderHolidays(){let tb=$('holidayBody');tb.innerHTML='';state.holidays.sort((a,b)=>String(a.date).localeCompare(String(b.date)));for(let h of state.holidays){let tr=document.createElement('tr');if(h.custom)tr.classList.add('holiday-custom');if(!h.enabled)tr.classList.add('muted-row');tr.innerHTML=`<td style="text-align:center"><input data-k="enabled" type="checkbox" ${h.enabled?'checked':''}></td><td><input data-k="date" type="date" value="${esc(h.date)}" ${h.custom?'':'readonly'}></td><td>${h.custom?`<input data-k="name" type="text" value="${esc(h.name)}">`:`<span>${esc(h.name)}</span>`}</td><td>${h.custom?'Extra sluiting':'Wettelijke feestdag'}</td><td>${h.custom?'<button class="btn danger" style="padding:4px 6px">×</button>':''}</td>`;tr.querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{h[el.dataset.k]=el.type==='checkbox'?el.checked:el.value;renderHolidays();changed()});let del=tr.querySelector('button');if(del)del.onclick=()=>{state.holidays=state.holidays.filter(x=>x.id!==h.id);renderHolidays();changed()};tb.appendChild(tr)}}
function addHoliday(){state.holidays.push({id:uid(),date:iso(new Date()),name:'Extra sluitingsdag',enabled:true,custom:true});renderHolidays();changed()}
function recalcOccupied(o){let a=D(o.anchor);if(!a)return;o.anchor=iso(a);o.anchor2=iso(add(a,168));if(!o.start1)o.start1=o.anchor;o.stop1=iso(add(a,112));if(!o.start2)o.start2=o.anchor2;o.stop2=iso(add(a,280))}
function occupiedIssues(o){let out=[],a=D(o.anchor);if(!a)return['Start 1 anker ontbreekt'];let p1=add(a,112),a2=add(a,168),p2=add(a,280);if(o.stop1&&!same(o.stop1,p1)&&!same(o.stop1,add(p1,-2)))out.push('Stop 1 wijkt af van +16 weken (of dinsdagfallback)');if(o.anchor2&&!same(o.anchor2,a2))out.push('Start 2 anker ≠ +24 weken');if(o.stop2&&!same(o.stop2,p2)&&!same(o.stop2,add(p2,-2)))out.push('Stop 2 wijkt af van +40 weken (of dinsdagfallback)');for(let k of ['stop1','stop2']){let d=D(o[k]);if(d&&!visitFree(d,'stop'))out.push(`${k==='stop1'?'Stop 1':'Stop 2'} valt op momenteel geblokkeerde datum`)}let map=occupiedStopMap();for(let d of [o.stop1,o.stop2])if(d&&(map.get(iso(d))||[]).filter(x=>x!==o.id).length)out.push(`Dubbele vaste Stop op ${fmt(d)}`);return[...new Set(out)]}
function renderOccupied(){let tb=$('occupiedBody');tb.innerHTML='';for(let o of state.occupied){let issues=occupiedIssues(o),tr=document.createElement('tr');tr.className='locked-row';tr.innerHTML=`<td><input data-k="id" type="text" value="${esc(o.id)}"></td><td><input data-k="anchor" type="date" value="${esc(o.anchor)}"></td><td><input data-k="start1" type="date" value="${esc(o.start1)}"></td><td><input data-k="stop1" type="date" value="${esc(o.stop1)}"></td><td><input data-k="anchor2" type="date" value="${esc(o.anchor2)}" readonly></td><td><input data-k="start2" type="date" value="${esc(o.start2)}"></td><td><input data-k="stop2" type="date" value="${esc(o.stop2)}"></td><td><input data-k="note" type="text" value="${esc(o.note)}">${issues.length?`<div class="issue">${esc(issues.join('; '))}</div>`:''}</td><td class="nowrap"><button class="btn secondary" data-recalc style="padding:4px 6px" title="Herbereken +16/+24/+40">↻</button> <button class="btn danger" data-del style="padding:4px 6px">×</button></td>`;tr.querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{let oldAnchor=o.anchor;o[el.dataset.k]=el.value;if(el.dataset.k==='anchor'&&o.anchor!==oldAnchor){let keep1=o.start1===oldAnchor||!o.start1,oldA2=o.anchor2,keep2=o.start2===oldA2||!o.start2;let a=D(o.anchor);o.anchor2=a?iso(add(a,168)):'';o.stop1=a?iso(add(a,112)):'';o.stop2=a?iso(add(a,280)):'';if(keep1)o.start1=o.anchor;if(keep2)o.start2=o.anchor2}renderOccupied();changed()});tr.querySelector('[data-recalc]').onclick=()=>{recalcOccupied(o);renderOccupied();changed()};tr.querySelector('[data-del]').onclick=()=>{state.occupied=state.occupied.filter(x=>x!==o);renderOccupied();changed()};tb.appendChild(tr)}$('occupiedCount').textContent=`${state.occupied.length} vast`}
function addOccupied(){let n=state.occupied.length+1;state.occupied.push(normaliseOccupied({id:`Patiënt ${n}`,anchor:'',start1:'',stop1:'',anchor2:'',start2:'',stop2:'',note:''}));renderOccupied();changed()}
function renderKPI(){let occ=state.occupied.length,nw=state.plan.length,allAnchors=[...state.occupied.map(o=>D(o.anchor)).filter(Boolean),...state.plan.map(p=>D(p.anchor)).filter(Boolean)],allEnds=[...state.occupied.map(o=>D(o.stop2)).filter(Boolean),...state.plan.map(p=>D(p.stop2)).filter(Boolean)];$('kOccupied').textContent=occ;$('kNew').textContent=nw;$('kTotal').textContent=occ+nw;if(!allAnchors.length||!allEnds.length){$('kLastStart').textContent='—';$('kEnd').textContent='—';$('kWeeks').textContent='—';return}let first=new Date(Math.min(...allAnchors)),lastA=new Date(Math.max(...allAnchors)),end=new Date(Math.max(...allEnds));$('kLastStart').textContent=fmt(lastA);$('kEnd').textContent=fmt(end);$('kWeeks').textContent=Math.round((end-first)/WEEK)}
function renderTimeline(){let box=$('timeline'),entities=[...state.occupied.map(o=>({kind:'locked',id:o.id,start1:D(o.start1||o.anchor),anchor:D(o.anchor),stop1:D(o.stop1),anchor2:D(o.anchor2),start2:D(o.start2||o.anchor2),stop2:D(o.stop2)})),...state.plan.map(p=>({kind:'plan',...p}))];if(!entities.length){box.innerHTML='<div class="small" style="padding:12px">Genereer een planning of voeg reeds ingenomen sloten toe.</div>';return}let ds=[];for(let p of entities)for(let k of ['start1','stop1','start2','stop2'])if(p[k])ds.push(D(p[k]));let min=add(new Date(Math.min(...ds)),-14),max=add(new Date(Math.max(...ds)),14),span=days(min,max),px=Math.max(2300,span*3.2),left=138,pos=d=>left+(days(min,d)/span)*(px-left-20);let html=`<div class="tl-inner" style="width:${px}px"><div class="tl-axis">`,m=new Date(min.getFullYear(),min.getMonth(),1,12);while(m<=max){html+=`<div class="month" style="left:${pos(m)}px">${m.toLocaleDateString('nl-BE',{month:'short',year:'numeric'})}</div>`;m=new Date(m.getFullYear(),m.getMonth()+1,1,12)}html+='</div>';for(let r of RES){html+=`<div class="lane"><span class="lane-label">${r}</span>`;let abs=[];for(let a of state.abs)if(resourcesOf(a).includes(r))abs.push({...a});if(r==='Hospital')for(let h of state.holidays.filter(x=>x.enabled))abs.push({start:h.date,end:h.date,reason:h.name,status:'Hard'});for(let a of abs){let s=D(a.start),e=D(a.end||a.start);if(!s||!e||e<min||s>max)continue;let l=pos(s),w=Math.max(8,pos(add(e,1))-l);html+=`<div class="block ${a.status==='Hard'?'':'soft'}" title="${esc(r+': '+a.reason)}" style="left:${l}px;width:${w}px">${esc(a.reason)}</div>`}html+='</div>'}for(let p of entities.sort((a,b)=>a.anchor-b.anchor)){let l=pos(p.start1),rr=pos(p.stop2),lock=p.kind==='locked'?' locked':'';html+=`<div class="lane"><span class="lane-label">${p.kind==='locked'?'🔒 ':''}${esc(p.id)}</span><div class="bar${lock}" style="left:${l}px;width:${rr-l}px"></div><i class="mark m-s1${lock}" title="Start 1 ${fmt(p.start1)}" style="left:${pos(p.start1)}px"></i><i class="mark m-p1${lock}" title="Stop 1 ${fmt(p.stop1)}" style="left:${pos(p.stop1)}px"></i><i class="mark m-s2${lock}" title="Start 2 ${fmt(p.start2)}" style="left:${pos(p.start2)}px"></i><i class="mark m-p2${lock}" title="Stop 2 ${fmt(p.stop2)}" style="left:${pos(p.stop2)}px"></i></div>`}html+='</div>';box.innerHTML=html}
function render(){renderPlan();renderReserve();renderKPI();renderTimeline();renderOccupied();renderHolidays()}
function serialise(p){let q={...p};for(let k of ['anchor','start1','anchor2','start2','stop1','stop1Protocol','stop2','stop2Protocol'])q[k]=iso(p[k]);return q}
function revive(p){let q={...p};for(let k of ['anchor','start1','anchor2','start2','stop1','stop1Protocol','stop2','stop2Protocol'])q[k]=D(p[k]);return q}
function project(){return{version:8,savedAt:new Date().toISOString(),settings:{rangeStart:$('rangeStart').value,rangeEnd:$('rangeEnd').value,targetN:$('targetN').value,leadDays:$('leadDays').value},abs:state.abs.map(normaliseAbs),holidays:state.holidays.map(normaliseHoliday),occupied:state.occupied.map(normaliseOccupied),plan:state.plan.map(serialise)}}
function apply(o){if(!o||!o.settings)throw Error('Ongeldig project');for(let [k,v] of Object.entries(o.settings))if($(k))$(k).value=v;state.abs=(o.abs||defaultAbs()).map(normaliseAbs);state.holidays=(Array.isArray(o.holidays)&&o.holidays.length?o.holidays:defaultHolidays()).map(normaliseHoliday);state.occupied=(o.occupied||[]).map(normaliseOccupied);state.plan=(o.plan||[]).map(revive);state.replaceId=null;state.bestFallback=null;renderAbs();renderHolidays();renderOccupied();buildReserve();render();save()}
function save(){try{localStorage.setItem(LS,JSON.stringify(project()));$('saveState').textContent='Lokaal opgeslagen '+new Date().toLocaleTimeString('nl-BE')}catch(e){$('saveState').textContent='Lokale opslag niet beschikbaar'}}
function changed(){state.bestFallback=null;hideFallback();buildReserve();render();save()}
async function xlsx(){if(window.XLSX)return true;return await new Promise(res=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=()=>res(true);s.onerror=()=>res(false);document.head.appendChild(s)})}
function absenceRows(){return state.abs.map(a=>{let rs=resourcesOf(a),o={Start:a.start,Einde:a.end,Reden:a.reason,Status:a.status};for(let r of RES)o[r]=rs.includes(r)?1:0;return o})}
function occupiedRows(){return state.occupied.map(o=>({ID:o.id,'Start 1 anker':o.anchor,'Start 1 visite':o.start1,'Stop 1':o.stop1,'Start 2 anker':o.anchor2,'Start 2 visite':o.start2,'Stop 2':o.stop2,Opmerking:o.note}))}
function planRows(includeOccupied=true){let rows=[];if(includeOccupied)for(let o of state.occupied)rows.push({'Patiënt / combinatie':o.id,Status:'Reeds ingenomen','Start 1 visite':o.start1,'Start 1 protocolanker':o.anchor,'Stop 1 (+16 weken)':o.stop1,'Stop 1 dag':wd(o.stop1),'Start 2 visite':o.start2,'Start 2 protocolanker (+24 weken)':o.anchor2,'Stop 2 (+40 weken)':o.stop2,'Stop 2 dag':wd(o.stop2),Beoordeling:'Vast','Reden / opmerking':o.note});for(let p of state.plan)rows.push({'Patiënt / combinatie':p.id,Status:'Nieuw beschikbaar','Start 1 visite':iso(p.start1),'Start 1 protocolanker':iso(p.anchor),'Stop 1 (+16 weken)':iso(p.stop1),'Stop 1 dag':wd(p.stop1),'Start 2 visite':iso(p.start2),'Start 2 protocolanker (+24 weken)':iso(p.anchor2),'Stop 2 (+40 weken)':iso(p.stop2),'Stop 2 dag':wd(p.stop2),Beoordeling:p.quality,'Reden / opmerking':p.reasons.join('; ')});return rows.sort((a,b)=>String(a['Start 1 protocolanker']).localeCompare(String(b['Start 1 protocolanker'])))}
async function exportSimple(){if(!await xlsx()){alert('Excelmodule kon niet laden.');return}let wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(planRows(true));ws['!cols']=[{wch:20},{wch:18},{wch:17},{wch:23},{wch:20},{wch:12},{wch:17},{wch:27},{wch:20},{wch:12},{wch:16},{wch:60}];XLSX.utils.book_append_sheet(wb,ws,'Patiëntcombinaties');XLSX.writeFile(wb,'SAFER_Fontan_patientcombinaties.xlsx')}
async function exportFull(){if(!await xlsx()){alert('Excelmodule kon niet laden.');return}let wb=XLSX.utils.book_new(),summary=[{Doel:+$('targetN').value,Reeds_ingenomen:state.occupied.length,Nieuw_gepland:state.plan.length,Totaal:state.occupied.length+state.plan.length,Laatste_inclusie:combinedLastAnchor()?iso(combinedLastAnchor()):'',Laatste_Stop2:combinedEnd()?iso(combinedEnd()):'',Totale_weken:combinedEnd()&&combinedFirstAnchor()?Math.round((combinedEnd()-combinedFirstAnchor())/WEEK):''}],r=state.reserve.slice(0,150).map(x=>({Start1_anker:iso(x.anchor),Stop1:iso(x.stop1),Stop1_dag:wd(x.stop1),Start2_anker:iso(x.anchor2),Stop2:iso(x.stop2),Stop2_dag:wd(x.stop2),Categorie:x.category,Kwaliteit:x.quality,Redenen:x.reasons.join('; ')})),h=state.holidays.map(x=>({Blokkeren:x.enabled?1:0,Datum:x.date,Naam:x.name,Type:x.custom?'Extra sluiting':'Wettelijke feestdag'}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(summary),'Samenvatting');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(planRows(true)),'Planning');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(occupiedRows()),'Ingenomen sloten');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(absenceRows()),'Afwezigheden');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(h),'Feestdagen');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r),'Reserve');XLSX.writeFile(wb,'SAFER_Fontan_planning.xlsx')}
async function exportAbs(){if(!await xlsx()){alert('Excelmodule kon niet laden.');return}let wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(absenceRows());XLSX.utils.book_append_sheet(wb,ws,'Afwezigheden');XLSX.writeFile(wb,'SAFER_Fontan_afwezigheden.xlsx')}
async function exportOccupied(){if(!await xlsx()){alert('Excelmodule kon niet laden.');return}let wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(occupiedRows());XLSX.utils.book_append_sheet(wb,ws,'Ingenomen sloten');XLSX.writeFile(wb,'SAFER_Fontan_ingenomen_sloten.xlsx')}
function parseCSV(t){let lines=t.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim()),delim=(lines[0]||'').includes(';')?';':',';let sp=l=>{let a=[],c='',q=false;for(let i=0;i<l.length;i++){let z=l[i];if(z==='"'){if(q&&l[i+1]==='"'){c+='"';i++}else q=!q}else if(z===delim&&!q){a.push(c);c=''}else c+=z}a.push(c);return a},h=sp(lines.shift()).map(x=>x.trim());return lines.map(l=>{let v=sp(l),o={};h.forEach((k,i)=>o[k]=v[i]||'');return o})}
function dateCellImport(v){if(v instanceof Date&&!isNaN(v))return iso(v);if(typeof v==='number'){let d=new Date(Math.round((v-25569)*DAY));if(!isNaN(d))return iso(d)}let s=String(v??'').trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);let m=s.match(/^(\d{1,2})[-\/.](\d{1,2})[-\/.](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:s.slice(0,10)}
function importRows(rows){let lc=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[String(k).toLowerCase().trim(),v])),n=0;for(let raw of rows){let o=lc(raw),start=o.start||o.startdatum||o.van,end=o.einde||o.end||o.einddatum||o.tot,reason=o.reden||o.reason||o.omschrijving||'',status=o.status||'Hard';if(!start)continue;let resources=[];for(let r of RES){let key=r.toLowerCase();if(truthy(o[key]))resources.push(r)}let oldResource=o.resource||o.persoon||o.wie;if(!resources.length&&RES.includes(String(oldResource)))resources=[String(oldResource)];if(!resources.length)continue;state.abs.push(normaliseAbs({id:uid(),resources,start:dateCellImport(start),end:dateCellImport(end||start),reason:String(reason),status}));n++}renderAbs();changed();alert(`${n} afwezigheden geïmporteerd. Bestaande rijen zijn behouden.`)}
async function importFile(f){let ext=f.name.split('.').pop().toLowerCase();if(ext==='csv'){let r=new FileReader();r.onload=()=>importRows(parseCSV(r.result));r.readAsText(f)}else{if(!await xlsx()){alert('Excelmodule kon niet laden.');return}let r=new FileReader();r.onload=()=>{let wb=XLSX.read(r.result,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]];importRows(XLSX.utils.sheet_to_json(ws,{defval:'',raw:true}))};r.readAsArrayBuffer(f)}}
function showTab(id){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===id));document.querySelectorAll('.pane').forEach(p=>p.classList.toggle('hidden',p.id!==id))}
function init(){state.abs=defaultAbs();state.holidays=defaultHolidays();state.occupied=[];let saved=localStorage.getItem(LS)||localStorage.getItem(OLDLS);if(saved){try{apply(JSON.parse(saved))}catch(e){renderAbs();renderHolidays();renderOccupied();render();save()}}else{renderAbs();renderHolidays();renderOccupied();render();save()}$('searchFrom').value=$('rangeStart').value;$('addAbs').onclick=addAbs;$('importAbs').onclick=()=>$('absFile').click();$('absFile').onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]);e.target.value=''};$('exportAbs').onclick=exportAbs;$('enableAllHolidays').onclick=()=>{state.holidays.forEach(h=>h.enabled=true);renderHolidays();changed()};$('disableAllHolidays').onclick=()=>{state.holidays.forEach(h=>h.enabled=false);renderHolidays();changed()};$('addHoliday').onclick=addHoliday;$('addOccupied').onclick=addOccupied;$('exportOccupied').onclick=exportOccupied;$('autoPlan').onclick=autoPlan;$('useFallback').onclick=useFallback;$('refreshReserve').onclick=()=>{buildReserve();renderReserve();save()};$('findBest').onclick=()=>{buildReserve();renderReserve();showTab('reservePane')};$('exportSimple').onclick=exportSimple;$('exportFull').onclick=exportFull;$('saveProject').onclick=()=>dl('SAFER_Fontan_project.json',JSON.stringify(project(),null,2));$('loadProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{apply(JSON.parse(r.result))}catch(x){alert(x.message)}};r.readAsText(f);e.target.value=''};$('reset').onclick=()=>{if(confirm('Huidige simulatie resetten?')){state={abs:defaultAbs(),holidays:defaultHolidays(),occupied:[],plan:[],reserve:[],replaceId:null,bestFallback:null};renderAbs();renderHolidays();renderOccupied();hideFallback();render();save()}};['rangeStart','rangeEnd','targetN','leadDays'].forEach(id=>$(id).onchange=changed);$('showTue').onchange=renderReserve;$('searchFrom').onchange=renderReserve;document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>showTab(t.dataset.tab));buildReserve();render()}
init();